name: Terraform Test Runner

on: [pull_request]

jobs:
  test:
    runs-on:
      group: arc-public-large-arm64-runner
    steps:
      - name: Check out code
        uses: actions/checkout@master

      - name: terraform test
        uses: dflook/terraform-test@58481fc46588861db38966e076b8481402817b91
